name: Push

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

env:
  BUILD_SH: build.sh

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Get REPO'
      run: |
        echo "REPO=$(echo $GITHUB_REPOSITORY | sed 's/WE1ZARD\///')" >> $GITHUB_ENV

    - name: 'Get Version'
      run: |
        echo "version=$(sed -n 1p ./update_log.md | sed "s/##\s//")" >> $GITHUB_ENV

    - name: 'Git Clone'
      run: |
        git clone --recursive https://WE1ZARD:${{ secrets.MAGIC_TOKEN }}@github.com/WE1ZARD/Magic-Suite-NX.git
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Magic/releases/latest | jq '.assets' | jq '.[1].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_Magic.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Settings/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_Settings.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Updater/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_Updater.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Guides/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_Guides.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/R2Config/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o package_R2Config.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/ultracam/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o ultracam.zip
        
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/EdiZon-Overlay/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o EdiZon-Overlay.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/FPSLocker/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o FPSLocker.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/SaltyNX/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o SaltyNX.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/ReverseNX-RT/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o ReverseNX-RT.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Status-Monitor-Overlay/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o Status-Monitor-Overlay.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/sys-clk-oc/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o sys-clk-oc.zip
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/Tesla-Pro-Overlay/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o Tesla-Pro-Overlay.zip
        
        curl -sL -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -sL https://api.github.com/repos/WE1ZARD/FanControl/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.MAGIC_TOKEN }}" -H 'Accept:application/octet-stream' -o FanControl.zip

        curl -sL https://api.github.com/repos/xfangfang/wiliwili/releases | jq '.[0].assets' | jq '.[8].browser_download_url' | xargs -I {} curl -sL {} -o wiliwili.zip
        unzip -oq wiliwili.zip
        rm wiliwili.zip
        mkdir ./switch
        mv ./wiliwili/wiliwili.nro ./switch
        zip -rq 'wiliwili.zip' ./switch
        rm -rf ./switch
        
    - name: 'Build'
      run: |
        chmod +x ./Magic-Suite-NX/$BUILD_SH
        ./Magic-Suite-NX/$BUILD_SH
        mv ./Magic-Suite-NX/update_log.md ./
        mv ./Magic-Suite-NX/user_guide.md ./
        cp ./update_log.md ./release_note.md
        echo -e "[![QQ](https://img.shields.io/badge/Q%E7%BE%A4-737375560-%233385d6?labelColor=%23393939)](https://qm.qq.com/q/RYsABoQpi0 '加入QQ群') [![Donate](https://img.shields.io/badge/%E7%88%B1%E5%8F%91%E7%94%B5-%E8%AF%B7%E6%88%91%E5%96%9D%E5%8F%AF%E4%B9%90-%23b01419?labelColor=%231e1e1e)](https://afdian.com/a/weizard/plan '请我喝可乐')[![Firmware](https://img.shields.io/badge/%E5%9B%BA%E4%BB%B6-18.1.0-%2397c900?labelColor=%23393939)](http://mirror.ghproxy.com/https://github.com/WE1ZARD/NX-Firmwares/releases/download/Latest/Firmware-Global.zip '下载固件')\n\n<details>\n<summary>更新日志</summary>\n\n$(cat ./release_note.md)" > ./release_note.md
        cat >> ./release_note.md << EOF
        </details>
        
        ![releases](https://img.shields.io/github/downloads/WE1ZARD/Magic-Suite/total)
        EOF
        echo -e "[![Magic Suite](https://pic.imgdb.cn/item/6682614cd9c307b7e99184c9.gif)](https://github.com/WE1ZARD/Magic-Suite)[![QQ](https://img.shields.io/badge/Q%E7%BE%A4-737375560-%233385d6?labelColor=%23393939)](https://qm.qq.com/q/RYsABoQpi0 '加入QQ群') [![Donate](https://img.shields.io/badge/%E7%88%B1%E5%8F%91%E7%94%B5-%E8%AF%B7%E6%88%91%E5%96%9D%E5%8F%AF%E4%B9%90-%23b01419?labelColor=%231e1e1e)](https://afdian.com/a/weizard/plan '请我喝可乐')[![Firmware](https://img.shields.io/badge/%E5%9B%BA%E4%BB%B6-18.1.0-%2397c900?labelColor=%23393939)](http://mirror.ghproxy.com/https://github.com/WE1ZARD/NX-Firmwares/releases/download/Latest/Firmware-Global.zip '下载固件') [![magic](https://img.shields.io/badge/%E4%B8%8B%E8%BD%BD-Magic_Suite-%2325c2a0?labelColor=%23393939)](https://mirror.ghproxy.com/https://github.com/WE1ZARD/Magic-Suite/releases/download/Pre-Release/AIO.zip '下载整合包')\n\n$(cat ./update_log.md)" > ./update_log.md
        echo -e "[![Magic Suite](https://pic.imgdb.cn/item/6682614cd9c307b7e99184c9.gif)](https://github.com/WE1ZARD/Magic-Suite)[![QQ](https://img.shields.io/badge/Q%E7%BE%A4-737375560-%233385d6?labelColor=%23393939)](https://qm.qq.com/q/RYsABoQpi0 '加入QQ群') [![Donate](https://img.shields.io/badge/%E7%88%B1%E5%8F%91%E7%94%B5-%E8%AF%B7%E6%88%91%E5%96%9D%E5%8F%AF%E4%B9%90-%23b01419?labelColor=%231e1e1e)](https://afdian.com/a/weizard/plan '请我喝可乐')[![Firmware](https://img.shields.io/badge/%E5%9B%BA%E4%BB%B6-18.1.0-%2397c900?labelColor=%23393939)](http://mirror.ghproxy.com/https://github.com/WE1ZARD/NX-Firmwares/releases/download/Latest/Firmware-Global.zip '下载固件') [![magic](https://img.shields.io/badge/%E4%B8%8B%E8%BD%BD-Magic_Suite-%2325c2a0?labelColor=%23393939)](https://mirror.ghproxy.com/https://github.com/WE1ZARD/Magic-Suite/releases/download/Pre-Release/AIO.zip '下载整合包')\n\n$(cat ./user_guide.md)" > ./user_guide.md
        zip -rq 'AIO.zip' ./Magic-Suite ./bootloader ./update_log.md ./user_guide.md ./LICENSE

    - name: 'Release'
      uses: softprops/action-gh-release@master
      with:
        body_path: ./release_note.md
        tag_name: '${{env.version}}'
        files: |
          AIO.zip
          package_Magic.zip
          package_Settings.zip
          package_Updater.zip
          package_R2Config.zip
          package_Guides.zip
          ultracam.zip
          wiliwili.zip
          EdiZon-Overlay.zip
          FPSLocker.zip
          SaltyNX.zip
          ReverseNX-RT.zip
          Status-Monitor-Overlay.zip
          sys-clk-oc.zip
          Tesla-Pro-Overlay.zip

    - name: 'Pre-Release'
      uses: softprops/action-gh-release@master
      with:
        body_path: ./release_note.md
        prerelease: true
        tag_name: 'Pre-Release'
        files: |
          AIO.zip
          package_Magic.zip
          package_Settings.zip
          package_Updater.zip
          package_R2Config.zip
          package_Guides.zip
          ultracam.zip
          wiliwili.zip
          EdiZon-Overlay.zip
          FPSLocker.zip
          SaltyNX.zip
          ReverseNX-RT.zip
          Status-Monitor-Overlay.zip
          sys-clk-oc.zip
          Tesla-Pro-Overlay.zip